apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;

        location / {
            root /var/www/html;
            try_files $uri /index.html;
        }
    }
